name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer
        swift build -v
    - name: Run tests
      run: |
        sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer
        swift test -v
